import uuid
from datetime import datetime

import pytest
from pydantic import ValidationError

from app.models.user_event import EventType, Mode, UserEvent
from app.models.venue import Venue, VenueProfile
from app.schemas.venue import (
    UserEventCreate,
    UserEventResponse,
    VenueCreate,
    VenueProfileResponse,
    VenueResponse,
    VenueWithProfile,
    user_event_from_create,
    user_event_to_response,
    venue_from_create,
    venue_profile_to_response,
    venue_to_response,
)

# ============================================================================
# VenueCreate Tests
# ============================================================================


def test_venue_create_schema():
    """Test VenueCreate schema validation."""
    venue = VenueCreate(
        provider_id="ChIJN1t_tDeuEmsRUsoyG83frY4",
        provider_name="google",
        name="Blue Bottle Coffee",
        categories=["cafe", "coffee_shop"],
        lat=37.7749,
        lng=-122.4194,
        address="66 Mint St, San Francisco, CA",
        rating=4.5,
        price_level=2,
    )

    assert venue.name == "Blue Bottle Coffee"
    assert venue.lat == 37.7749
    assert venue.categories == ["cafe", "coffee_shop"]
    assert venue.rating == 4.5
    assert venue.price_level == 2


def test_venue_create_validation():
    """Test that invalid data raises validation errors."""
    with pytest.raises(ValidationError):
        VenueCreate(
            provider_id="test",
            provider_name="google",
            name="Test",
            lat=37.7749,
            lng=-122.4194,
            rating=10,  # Invalid: rating > 5
        )


def test_venue_create_optional_fields():
    """Test VenueCreate with optional fields."""
    venue = VenueCreate(
        provider_id="test123",
        provider_name="google",
        name="Test Venue",
        lat=37.7749,
        lng=-122.4194,
        # Optional fields not provided
    )

    assert venue.address is None
    assert venue.rating is None
    assert venue.price_level is None
    assert venue.categories == []  # Default empty list


# ============================================================================
# Venue Conversion Tests
# ============================================================================


def test_venue_from_create():
    """Test conversion from VenueCreate to dict."""
    venue_create = VenueCreate(
        provider_id="test123",
        provider_name="google",
        name="Test Venue",
        categories=["cafe"],
        lat=37.7749,
        lng=-122.4194,
    )

    venue_dict = venue_from_create(venue_create)

    assert "provider_id" in venue_dict
    assert venue_dict["name"] == "Test Venue"
    assert venue_dict["lat"] == 37.7749
    assert "id" not in venue_dict  # Should not include id (generated by DB)


def test_venue_to_response():
    """Test conversion from Venue model to VenueResponse schema."""
    venue_id = uuid.uuid4()
    venue_model = Venue(
        id=venue_id,
        provider_id="test123",
        provider_name="google",
        name="Test Venue",
        categories=["cafe"],
        lat=37.7749,
        lng=-122.4194,
        rating=4.5,
        created_at=datetime.now(),
        updated_at=datetime.now(),
        last_seen_at=datetime.now(),
    )

    venue_response = venue_to_response(venue_model)

    assert isinstance(venue_response, VenueResponse)
    assert venue_response.id == venue_id
    assert venue_response.name == "Test Venue"
    assert venue_response.rating == 4.5
    assert venue_response.categories == ["cafe"]


def test_venue_to_response_with_profile():
    """Test venue_to_response with profile included."""
    venue_id = uuid.uuid4()
    profile_id = uuid.uuid4()

    venue_model = Venue(
        id=venue_id,
        provider_id="test123",
        provider_name="google",
        name="Test Venue",
        categories=["cafe"],
        lat=37.7749,
        lng=-122.4194,
        created_at=datetime.now(),
        updated_at=datetime.now(),
        last_seen_at=datetime.now(),
    )

    profile_model = VenueProfile(
        id=profile_id,
        venue_id=venue_id,
        attribute_scores={"quiet": 0.85, "laptop_friendly": 0.72},
        evidence_snippets={"quiet": ["Great for studying"]},
        profiled_at=datetime.now(),
    )

    venue_model.profile = profile_model
    venue_with_profile = venue_to_response(venue_model, include_profile=True)

    assert isinstance(venue_with_profile, VenueWithProfile)
    assert venue_with_profile.profile is not None
    assert venue_with_profile.profile.venue_id == venue_id
    assert "quiet" in venue_with_profile.profile.attribute_scores


# ============================================================================
# VenueProfile Tests
# ============================================================================


def test_venue_profile_to_response():
    """Test conversion from VenueProfile model to VenueProfileResponse schema."""
    profile_id = uuid.uuid4()
    venue_id = uuid.uuid4()

    profile_model = VenueProfile(
        id=profile_id,
        venue_id=venue_id,
        attribute_scores={"quiet": 0.85, "laptop_friendly": 0.72},
        evidence_snippets={"quiet": ["Great for studying"], "laptop_friendly": ["Has outlets"]},
        profiled_at=datetime.now(),
    )

    profile_response = venue_profile_to_response(profile_model)

    assert isinstance(profile_response, VenueProfileResponse)
    assert profile_response.id == profile_id
    assert profile_response.venue_id == venue_id
    assert "quiet" in profile_response.attribute_scores
    assert profile_response.attribute_scores["quiet"] == 0.85
    assert len(profile_response.evidence_snippets["quiet"]) == 1


# ============================================================================
# UserEvent Tests
# ============================================================================


def test_user_event_create():
    """Test UserEventCreate schema."""
    event = UserEventCreate(
        user_id="user123",
        event_type=EventType.CLICK,
        mode=Mode.WORK,
        query_context={"lat": 37.7749, "lng": -122.4194, "radius": 1000},
    )

    assert event.user_id == "user123"
    assert event.event_type == EventType.CLICK
    assert event.mode == Mode.WORK
    assert event.query_context["lat"] == 37.7749


def test_user_event_create_optional_fields():
    """Test UserEventCreate with optional fields."""
    event = UserEventCreate(
        event_type=EventType.IMPRESSION,
        # Optional fields not provided
    )

    assert event.user_id is None
    assert event.venue_id is None
    assert event.mode is None
    assert event.query_context is None


def test_user_event_from_create():
    """Test conversion from UserEventCreate to dict."""
    event_create = UserEventCreate(
        user_id="user123",
        event_type=EventType.CLICK,
        mode=Mode.WORK,
        query_context={"lat": 37.7749, "lng": -122.4194},
    )

    event_dict = user_event_from_create(event_create)

    assert "user_id" in event_dict
    assert event_dict["event_type"] == EventType.CLICK
    assert event_dict["mode"] == Mode.WORK
    assert "id" not in event_dict  # Should not include id (generated by DB)


def test_user_event_to_response():
    """Test conversion from UserEvent model to UserEventResponse schema."""
    event_id = uuid.uuid4()
    venue_id = uuid.uuid4()

    event_model = UserEvent(
        id=event_id,
        user_id="user123",
        event_type=EventType.CLICK,
        venue_id=venue_id,
        mode=Mode.WORK,
        query_context={"lat": 37.7749, "lng": -122.4194, "radius": 1000},
        created_at=datetime.now(),
    )

    event_response = user_event_to_response(event_model)

    assert isinstance(event_response, UserEventResponse)
    assert event_response.id == event_id
    assert event_response.user_id == "user123"
    assert event_response.event_type == EventType.CLICK
    assert event_response.mode == Mode.WORK
    assert event_response.venue_id == venue_id
