"""Initial migration

Revision ID: f99aa361bd09
Revises: 
Create Date: 2026-01-12 16:46:21.436503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99aa361bd09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('hours', sa.JSON(), nullable=True),
    sa.Column('raw_hours', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_index(op.f('ix_venues_provider_id'), 'venues', ['provider_id'], unique=True)
    op.create_table('user_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.Enum('IMPRESSION', 'CLICK', 'SAVE', 'THUMBS_UP', 'THUMBS_DOWN', 'NAVIGATE', name='event_type_enum'), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.Enum('WORK', 'DATE', 'QUICK_BITE', 'BUDGET', name='mode_enum'), nullable=True),
    sa.Column('query_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_events_created_at'), 'user_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_events_event_type'), 'user_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_events_id'), 'user_events', ['id'], unique=False)
    op.create_index(op.f('ix_user_events_mode'), 'user_events', ['mode'], unique=False)
    op.create_index(op.f('ix_user_events_user_id'), 'user_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_events_venue_id'), 'user_events', ['venue_id'], unique=False)
    op.create_table('venue_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('attribute_scores', sa.JSON(), nullable=False),
    sa.Column('evidence_snippets', sa.JSON(), nullable=False),
    sa.Column('embedding_ref', sa.String(length=255), nullable=True),
    sa.Column('profiled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_profiles_id'), 'venue_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_venue_profiles_venue_id'), 'venue_profiles', ['venue_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venue_profiles_venue_id'), table_name='venue_profiles')
    op.drop_index(op.f('ix_venue_profiles_id'), table_name='venue_profiles')
    op.drop_table('venue_profiles')
    op.drop_index(op.f('ix_user_events_venue_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_user_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_mode'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_event_type'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_created_at'), table_name='user_events')
    op.drop_table('user_events')
    op.drop_index(op.f('ix_venues_provider_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###
